### ISSUE TITLE
Streamline Docker image tagging

### ISSUE THREAD

**Issue by tomkerkhove** [tomkerkhove/containo#34]
Streamline Docker image tagging so that you can push "full" images and "preview" images.

The build should:
- Build & push images with the tags `latest` & version when no tag was specified
- Build & push images with the `dev` tag and the tag that was specified when queueing the build
- Only build & push images if codebase has changed

## Overview
- [ ] Change build spec
- [ ] Update build documentation

**Comment by tomkerkhove** [comment]
Should be possible similar to this:
```yaml
queue:
  name: Hosted VS2017
  condition: succeeded()
#Your build definition references the ‘Tag.Name’ variable, which you’ve selected to be settable at queue time. Create or edit the build definition for this YAML file, define the variable on the Variables tab, and then select the option to make it settable at queue time. See https://go.microsoft.com/fwlink/?linkid=865971
steps:
- powershell: |
   # Write your powershell commands here.
   
   Write-Host "Empty Variable" 
  displayName: PowerShell Script
  condition: eq(variables['Tag.Name'], '')

- powershell: |
   # Write your powershell commands here.
   
   Write-Host "$(Tag.Name)"
   
   # Use the environment variables input below to pass secret variables to this script. 
  displayName: PowerShell Script (Prerelease)
  condition: ne(variables['Tag.Name'], '')


```
